### ISSUE TITLE
Kitura 3 depends on 'loggerapi' 2.0.0..<3.0.0.

### ISSUE THREAD

**Issue by icyield** [Kitura/FileKit#15]
This package needs an update to loggerapi

 .package(url: "https://github.com/Kitura/LoggerAPI.git", from: "2.0.0" )

But I use this package via https://github.com/Kitura/Configuration -> https://github.com/Kitura/Swift-cfenv -> https://github.com/Kitura/CloudEnvironment 

So the whole chain needs updates.

**Comment by dannys42** [comment]
@icyield Please try FileKit 1.1.0 and Configuration 3.1.0.  If that still doesn't work, would you mind sharing your Package.swift file so I can see the full dependency list?

**Comment by icyield** [comment]
That works. Thanks. 

My package that had the issue is a "common" package that I use for a number of different apps. When I then include that package in the apps Package.swift I get errors for Kitura-CORs. I suspected that there are a lot of packages in the Kitura tree that might be using,
 .package(url: "https://github.com/Kitura/Kitura.git", .upToNextMajor(from: "2.9.200")),

that will now need updated.
